### ISSUE TITLE
. Or _

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/afscOM#1]
https://github.com/BenWilliams-NOAA/afscOM/blob/be79ef18076157b19e9316a8f3663d70eb3260be/R/catch_utils.R#L13

@Ovec8hkin one thing to consider is using ‘.’ or ‘_’ in function names. There’s currently some flip flopping. My preference is underscores as dots have specific meanings if using data.table or purrr. But can be convinced otherwise - so long as there is logical consistency.

**Comment by Ovec8hkin** [comment]
I don't have a preference. I have, to some degree, historically used `.` syntax for variables and `_` syntax for functions, but not married to either.

**Comment by Ovec8hkin** [comment]
official tidyverse docs advise using "_" so I will go with that moving forward.
