### ISSUE TITLE
Allow for specifying fishery fleet and survey fleet selectivity using in one selectivity matrix

### ISSUE THREAD

**Issue by Ovec8hkin** [BenWilliams-NOAA/afscOM#9]
Current, fishery selectivity and survey selectivity must be defined as separate demographic parameter matrices and each added separately to the larger `dem_params` list. It would be handy to be able to specify them in a single `dem_params$selex` matrix rather than separately.

This can be naively achieved by having users specify `nfleets` as `n_fish_fleets + n_surv_fleets` and then specify which fleets are survey fleets in the `model_options` list. That option can be reference by the `simulate_catch` function and the `simulate_observation` function to correctly apply selectivity to the fishery and survey fleets.

**Comment by chengmatt** [comment]
I don't really like this tbh, but others might think differently. I think from a user perspective, it might be better to be more explicit and clear as to what's a survey fleet and what's a fishery fleet.

**Comment by Ovec8hkin** [comment]
@chengmatt Im also not the biggest fan of this style, but it's reminiscent of how Stock Synthesis handles fleets, which is why I thought of it first. 

Having separate fishing and survey selectivity matrices also feels obtuse to me though. Would be interested to hear if you have other thoughts as to how to differentiate between the two fleet types.

**Comment by BenWilliams-NOAA** [comment]
I've stumbled around on this issue a couple times, gets real ugly when also trying to generalize to include which fleets do/don't have comps and whether the comps are combined sex. From a coder perspective it is nice to have everything rolled into one, but as @chengmatt mentioned it isn't always clear from a user perspective. I guess I lean toward discrete user supplied inputs end up being clearer than loads of switches.

**Comment by chengmatt** [comment]
Yeah second what @BenWilliams-NOAA said. I think this is how you have it coded right now, so what you have is probably fine? Less work on your end as well.

**Comment by Ovec8hkin** [comment]
Okay. Sounds good.
